title: Site Title
favicon: assets/images/favicon.ico
ogTitle: Site Title
ogType: website
ogDescription: Lorem Ipsum
ogImage: assets/images/site-preview.png
ogUrl: https://website.com
email: email@sample.com
twitterUrl: http://www.twitter.com/
linkedInUrl: https://www.linkedin.com/
facebookUrl: https://www.facebook.com/
googleAnalyticsId: ""
markdown: kramdown
source: src/jekyll
destination: dist
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - package-lock.json